set_property PACKAGE_PIN G14 [get_ports k2]
set_property IOSTANDARD LVCMOS33 [get_ports k2]
set_property IOSTANDARD LVCMOS33 [get_ports led29]
set_property IOSTANDARD LVCMOS33 [get_ports led31]
set_property IOSTANDARD LVCMOS33 [get_ports led32]
set_property PACKAGE_PIN H15 [get_ports led29]
set_property PACKAGE_PIN G15 [get_ports led31]
set_property PACKAGE_PIN N15 [get_ports led32]
